---
title: "5. AlphaDiversity_Handout.Rmd"
output: html_document
date: "2025-01-24"
---

# Observed richness

```{r}
data(BCI)
dim(BCI)
S.obs <- function(x = ""){
  rowSums(x > 0) * 1
}
S.obs(BCI)
specnumber(BCI)
```
## Coverage

```{r}
C <- function(x = ""){
  1 - (rowSums(x== 1) / rowSums(x))
}
C(BCI)
```

## Estimated Richness

```{r}
soilbac <- read.table("data/soilbac.txt", sep = "\t", header= TRUE, row.names = 1)
soilbac.t <- as.data.frame(t(soilbac))
soilbac1 <- soilbac.t[1,]
```

```{r}
S.chao1 <- function(x = ""){
  S.obs(x) + (sum(x == 1)^2) / (2 * sum(x == 2))
}
S.chao1(soilbac1)
```

```{r}
S.chao2 <- function(site = "", SbyS =""){
  SbyS = as.data.frame(SbyS)
  x = SbyS[site, ]
  SbyS.pa <- (SbyS > 0) * 1
  Q1 = sum(colSums(SbyS.pa) == 1)
  Q2 = sum(colSums(SbyS.pa) == 2)
  S.chao2 = S.obs(x) + (Q1^2)/(2 * Q2)
  return(S.chao2)
}
```

```{r}
S.ace <- function(x = "", tresh = 10){
  x <- x[x>0]
  S.abund <- length(which(x > tresh))
  S.rare <- length(which(x <= tresh))
  singlt <- length(which(x == 1))
  N.rare <- sum(x[which(x <= tresh)])
  C.ace <- 1 - (singlt / N.rare)
  i <- c(1:tresh)
  count <- function(i, y){
    length(y[y == i])
  }
  a.1 <- sapply(i, count, x)
  f.1 <- (i * (i - 1)) * a.1
  G.ace <- (S.rare/C.ace)*(sum(f.1)/(N.rare*(N.rare-1)))
  S.ace <- S.abund + (S.rare/C.ace) + (singlt/C.ace) * max(G.ace, 0)
  return(S.ace)
}
```

## Rarefaction

```{r}
soilbac.S <- S.obs(soilbac.t)
min.N <- min(rowSums(soilbac.t))
S.rarefy <- rarefy(x = soilbac.t, sample = min.N, se = TRUE)
rarecurve(x = soilbac.t, step = 20, col = "blue", cex = 0.6, las = 1)
abline(0, 1, col = 'red')
text(1500, 1500, "1:1", pos = 2, col = 'red')
```

# Species Evenness

## Rank-Abundance Curve

```{r}
RAC <- function(x = ""){
  x.ab = x[x > 0]
  x.ab.ranked = x.ab[order(x.ab, decreasing = TRUE)]
  as.data.frame(lapply(x.ab.ranked, unlist))
  return(x.ab.ranked)
}

plot.new()
site1 <- BCI[1, ]

rac <- RAC(x = site1)
ranks <- as.vector(seq(1, length(rac)))
opar <- par(no.readonly = TRUE)
par(mar = c(5.1, 5.1, 4.1, 2.1))
plot(ranks, log(rac), type = 'p', axes = F,
     xlab = "Rank in abundance", ylab = "Abudance",
     las = 1, cex.lab = 1.4, cex.axis = 1.25)

box()
axis(side = 1, labels = T, cex.axis = 1.25)
axis(side = 2, las = 1, cex.axis = 1.25,
     labels = c(1, 2, 5, 10, 20), at = log(c(1, 2, 5, 10, 20)))
```

## Simpson's Evenness

```{r}
par <- opar
SimpE <- function(x = ""){
 S <- S.obs(x)
 x = as.data.frame(x)
 D <- diversity(x, "inv")
 E <- (D)/S
 return(E)
}

site1 <- BCI[1, ]
SimpE(site1)
```

## Smith and Wilson's Evenness Index

```{r}

```